import {
  MessageCircle,
  Camera,
  MessageSquare,
  Send,
  Mail,
  Globe,
  Video,
  AtSign,
  Hash,
  Inbox,
  Users,
  History,
  StickyNote,
  Ticket,
  BarChart3,
  ShieldCheck,
  Bot,
  Filter,
  HelpCircle,
  UserCheck,
  BookOpen,
  Workflow,
  Route,
  ListChecks,
  Bell,
  TrendingUp,
  Zap,
  CheckCheck,
  Clock,
  Sparkles,
  GraduationCap,
  HeartPulse,
  Hotel,
  Factory,
  ShoppingBag,
  Landmark,
  HandHeart,
  Building2,
  Truck,
  Clapperboard,
  Smartphone,
  Gauge,
  ArrowRight,
  type LucideIcon,
} from "lucide-react";
import type { IconKey } from "@/content/site-content";

export const iconMap: Record<IconKey, LucideIcon> = {
  "message-circle": MessageCircle,
  camera: Camera,
  "message-square": MessageSquare,
  send: Send,
  mail: Mail,
  globe: Globe,
  video: Video,
  "at-sign": AtSign,
  hash: Hash,
  inbox: Inbox,
  users: Users,
  history: History,
  "sticky-note": StickyNote,
  ticket: Ticket,
  "bar-chart-3": BarChart3,
  "shield-check": ShieldCheck,
  bot: Bot,
  filter: Filter,
  "help-circle": HelpCircle,
  "user-check": UserCheck,
  "book-open": BookOpen,
  workflow: Workflow,
  route: Route,
  "list-checks": ListChecks,
  bell: Bell,
  "trending-up": TrendingUp,
  zap: Zap,
  "check-check": CheckCheck,
  clock: Clock,
  sparkles: Sparkles,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  hotel: Hotel,
  factory: Factory,
  "shopping-bag": ShoppingBag,
  landmark: Landmark,
  "hand-heart": HandHeart,
  "building-2": Building2,
  truck: Truck,
  clapperboard: Clapperboard,
  smartphone: Smartphone,
  gauge: Gauge,
  "arrow-right": ArrowRight,
};

export function Icon({
  name,
  className,
}: {
  name: IconKey;
  className?: string;
}) {
  const Component = iconMap[name];
  return <Component className={className} strokeWidth={1.75} aria-hidden="true" />;
}
